# nginx.conf
server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Todas las rutas deben redirigir a index.html (esto soluciona el error 404 al recargar en wouter/react-router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Caché automático para recursos estáticos para acelerar la carga en producción
    location ~* \.(?:ico|css|js|gif|jpe?g|png|webp|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }
}
